FROM --platform=$BUILDPLATFORM  golang:1.16 AS builder

ARG TARGETPLATFORM

WORKDIR /go/src/github.com/openshift/assisted-installer-agent

ENV GOFLAGS=-mod=mod
WORKDIR /go/src/github.com/openshift/assisted-installer

# Bring in the go dependencies before anything else so we can take
# advantage of caching these layers in future builds.
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .

RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then GO_BUILD_ENV_PARAMS="GOOS=linux GOARCH=arm64" make installer;else make installer; fi

FROM  --platform=$TARGETPLATFORM quay.io/centos/centos:centos8

COPY --from=builder /go/src/github.com/openshift/assisted-installer/build/installer /usr/bin/installer
COPY --from=builder /go/src/github.com/openshift/assisted-installer/deploy/assisted-installer-controller /assisted-installer-controller/deploy

ENTRYPOINT ["/usr/bin/installer"]
